//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessModule
    {
        public System.Guid ModuleID { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleDesc { get; set; }
        public string ModuleTitle { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<int> ModuleLevel { get; set; }
        public Nullable<int> ModuleSeq { get; set; }
        public string ModuleLink { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSetting { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
