//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public string Orgzid { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string ContactPerson { get; set; }
        public string EmailAddress { get; set; }
        public string OrgzType { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<bool> IsBlacklist { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
