//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSendLog
    {
        public System.Guid EmailSendLogID { get; set; }
        public Nullable<System.Guid> RefID { get; set; }
        public Nullable<System.Guid> EmailTempID { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
    }
}
