//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eSTS_LiveEntities : DbContext
    {
        public eSTS_LiveEntities()
            : base("name=eSTS_LiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessGroup> AccessGroups { get; set; }
        public DbSet<AccessGroupModule> AccessGroupModules { get; set; }
        public DbSet<AccessModule> AccessModules { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }
        public DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public DbSet<EmailModule> EmailModules { get; set; }
        public DbSet<EmailSendLog> EmailSendLogs { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<FlowActionEmail> FlowActionEmails { get; set; }
        public DbSet<FlowActionStatu> FlowActionStatus { get; set; }
        public DbSet<FlowModuleLayer> FlowModuleLayers { get; set; }
        public DbSet<LicCompany> LicCompanies { get; set; }
        public DbSet<LicCompanyAttach> LicCompanyAttaches { get; set; }
        public DbSet<LicCompanyVessel> LicCompanyVessels { get; set; }
        public DbSet<LicCompanyVesselAttach> LicCompanyVesselAttaches { get; set; }
        public DbSet<log> logs { get; set; }
        public DbSet<ModuleAttachDoc> ModuleAttachDocs { get; set; }
        public DbSet<MSDeliveryLoc> MSDeliveryLocs { get; set; }
        public DbSet<MSDocType> MSDocTypes { get; set; }
        public DbSet<MSOilCategory> MSOilCategories { get; set; }
        public DbSet<MSOilClass> MSOilClasses { get; set; }
        public DbSet<MSOilType> MSOilTypes { get; set; }
        public DbSet<MSPermitIssuer> MSPermitIssuers { get; set; }
        public DbSet<MSPortLocation> MSPortLocations { get; set; }
        public DbSet<MSSupplyMethod> MSSupplyMethods { get; set; }
        public DbSet<MSUOM> MSUOMs { get; set; }
        public DbSet<OpAppointAgent> OpAppointAgents { get; set; }
        public DbSet<OpCaseNum> OpCaseNums { get; set; }
        public DbSet<OperationApp> OperationApps { get; set; }
        public DbSet<OperationAppAttach> OperationAppAttaches { get; set; }
        public DbSet<OperationAppFlow> OperationAppFlows { get; set; }
        public DbSet<OwnerInfo> OwnerInfoes { get; set; }
        public DbSet<PendingEmail> PendingEmails { get; set; }
        public DbSet<SystemParam> SystemParams { get; set; }
        public DbSet<TblMailServer> TblMailServers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<v_AccessGroupModule> v_AccessGroupModule { get; set; }
        public DbSet<v_AccessModule> v_AccessModule { get; set; }
        public DbSet<v_AdminUsers> v_AdminUsers { get; set; }
        public DbSet<v_AppointAgent> v_AppointAgent { get; set; }
        public DbSet<v_AppointAgentNew> v_AppointAgentNew { get; set; }
        public DbSet<v_FlowActionStatus> v_FlowActionStatus { get; set; }
        public DbSet<v_Integration> v_Integration { get; set; }
        public DbSet<v_IntegrationFlow> v_IntegrationFlow { get; set; }
        public DbSet<v_LicCompany> v_LicCompany { get; set; }
        public DbSet<v_LicCompanyActive> v_LicCompanyActive { get; set; }
        public DbSet<v_LicCompanyAttach> v_LicCompanyAttach { get; set; }
        public DbSet<v_LicCompanyVesselAttach> v_LicCompanyVesselAttach { get; set; }
        public DbSet<v_OperationApp> v_OperationApp { get; set; }
        public DbSet<v_OperationAppAttach> v_OperationAppAttach { get; set; }
        public DbSet<v_OperationAppFlow> v_OperationAppFlow { get; set; }
        public DbSet<v_opGroupEmail> v_opGroupEmail { get; set; }
        public DbSet<v_OpLicCompanyVessel> v_OpLicCompanyVessel { get; set; }
        public DbSet<v_Permit> v_Permit { get; set; }
        public DbSet<v_STSOperator> v_STSOperator { get; set; }
        public DbSet<v_SuppDoc> v_SuppDoc { get; set; }
        public DbSet<v_users> v_users { get; set; }
        public DbSet<v_UsersSASO> v_UsersSASO { get; set; }
    }
}
