//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowModuleLayer
    {
        public System.Guid FlowModuleLayerID { get; set; }
        public Nullable<System.Guid> FlowModuleID { get; set; }
        public Nullable<System.Guid> PortID { get; set; }
        public Nullable<int> ApprovalSeq { get; set; }
        public Nullable<System.Guid> MSPermitIssuer { get; set; }
        public Nullable<System.Guid> FlowActionID { get; set; }
        public Nullable<System.Guid> AccessGroupID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
