//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int log_seq { get; set; }
        public string log_activity_type { get; set; }
        public string log_activity { get; set; }
        public Nullable<System.DateTime> log_datetime { get; set; }
        public string log_remark { get; set; }
        public string logger { get; set; }
    }
}
