//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleAttachDoc
    {
        public System.Guid ModuleAttachID { get; set; }
        public string ModuleID { get; set; }
        public string ModuleDesc { get; set; }
        public Nullable<System.Guid> AttachTypeID { get; set; }
    }
}
