//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpCaseNum
    {
        public System.Guid id { get; set; }
        public Nullable<int> OpYear { get; set; }
        public string CaseNumPG { get; set; }
        public string CaseNumTp { get; set; }
    }
}
