//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationAppFlow
    {
        public System.Guid OperationAppFlowID { get; set; }
        public Nullable<System.Guid> OperationAppID { get; set; }
        public string CompID { get; set; }
        public Nullable<System.Guid> FlowActionStatusID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsReject { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ActionBy { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Remark { get; set; }
    }
}
