//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AccessGroupModule
    {
        public Nullable<long> UniqueId { get; set; }
        public System.Guid lvl0id { get; set; }
        public string lvl0Code { get; set; }
        public string lvl0Desc { get; set; }
        public string lvl0DescDisp { get; set; }
        public Nullable<int> lvl0Seq { get; set; }
        public string lvl0Link { get; set; }
        public Nullable<System.Guid> lvl1id { get; set; }
        public string lvl1Code { get; set; }
        public string lvl1Desc { get; set; }
        public string lvl1DescDisp { get; set; }
        public Nullable<int> lvl1Seq { get; set; }
        public string lvl1Link { get; set; }
        public Nullable<System.Guid> lvl2id { get; set; }
        public string lvl2Code { get; set; }
        public string lvl2Desc { get; set; }
        public string lvl2DescDisp { get; set; }
        public Nullable<int> lvl2Seq { get; set; }
        public string lvl2Link { get; set; }
    }
}
