//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AppointAgentNew
    {
        public System.Guid OpAppointAgentID { get; set; }
        public string SACompID { get; set; }
        public string SACompName { get; set; }
        public string SOCompID { get; set; }
        public string SOCompName { get; set; }
        public Nullable<System.DateTime> AppointStartDate { get; set; }
        public Nullable<System.DateTime> AppointEndDate { get; set; }
        public string AppointAttachLink { get; set; }
    }
}
