//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_LicCompany
    {
        public System.Guid LicCompanyID { get; set; }
        public string CompID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.Guid> LicenseID { get; set; }
        public string LicDateIssue { get; set; }
        public string LicDateExp { get; set; }
        public Nullable<System.DateTime> DtLicIssue { get; set; }
        public Nullable<System.DateTime> DtLicExp { get; set; }
        public Nullable<int> Location { get; set; }
        public string ServiceType { get; set; }
        public string CaseNUm { get; set; }
        public string ServiceCode { get; set; }
        public string PortName { get; set; }
        public string VesselName { get; set; }
        public string VesselIMO { get; set; }
        public string EmailAddress { get; set; }
    }
}
