//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_LicCompanyAttach
    {
        public System.Guid AttachID { get; set; }
        public Nullable<System.Guid> LicCompanyID { get; set; }
        public Nullable<System.Guid> AttachTypeID { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Path { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DocCode { get; set; }
        public string DocDesc { get; set; }
        public string ModuleDesc { get; set; }
        public string ModuleID { get; set; }
        public string DocType { get; set; }
        public Nullable<int> DocStatus { get; set; }
    }
}
