//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_OperationApp
    {
        public System.Guid OperationAppID { get; set; }
        public string CaseNum { get; set; }
        public string CompID { get; set; }
        public string SOCompID { get; set; }
        public string CompanyName { get; set; }
        public string SOCompanyName { get; set; }
        public Nullable<System.Guid> SOLicID { get; set; }
        public Nullable<System.Guid> SupplyMethodID { get; set; }
        public string MethodCode { get; set; }
        public string MedhodName { get; set; }
        public Nullable<System.Guid> DeliveryLocID { get; set; }
        public Nullable<int> Location { get; set; }
        public string DeliveryLocation { get; set; }
        public Nullable<System.Guid> PermitIssuerID { get; set; }
        public string PermitIssuer { get; set; }
        public Nullable<System.Guid> VSID { get; set; }
        public string VSIMONo { get; set; }
        public string VSName { get; set; }
        public string VSFlag { get; set; }
        public string VSFlagName { get; set; }
        public string VSPortReg { get; set; }
        public Nullable<double> VSLOA { get; set; }
        public Nullable<double> VSGRT { get; set; }
        public Nullable<double> VSNRT { get; set; }
        public string VSMMSINo { get; set; }
        public string VSCallSign { get; set; }
        public string VSLastPort { get; set; }
        public string VSLastPortName { get; set; }
        public string VSNextPort { get; set; }
        public string VSNextPortName { get; set; }
        public Nullable<int> VSLatDegree { get; set; }
        public Nullable<decimal> VSLatMin { get; set; }
        public Nullable<int> VSLongDegree { get; set; }
        public Nullable<decimal> VSLongMin { get; set; }
        public string VSLatitude { get; set; }
        public string VSLongitude { get; set; }
        public Nullable<System.Guid> VRID { get; set; }
        public string VRIMONo { get; set; }
        public string VRName { get; set; }
        public string VRFlag { get; set; }
        public string VRFlagName { get; set; }
        public string VRPortReg { get; set; }
        public Nullable<double> VRLOA { get; set; }
        public Nullable<double> VRGRT { get; set; }
        public Nullable<double> VRNRT { get; set; }
        public string VRMMSINo { get; set; }
        public string VRCallSign { get; set; }
        public string VRLastPort { get; set; }
        public string VRLastPortName { get; set; }
        public string VRNextPort { get; set; }
        public string VRNextPortName { get; set; }
        public Nullable<int> VRLatDegree { get; set; }
        public Nullable<decimal> VRLatMin { get; set; }
        public Nullable<int> VRLongDegree { get; set; }
        public Nullable<decimal> VRLongMin { get; set; }
        public string VRLatitude { get; set; }
        public string VRLongitude { get; set; }
        public Nullable<System.DateTime> EstOperationDateTime { get; set; }
        public Nullable<System.DateTime> EstOperationTime { get; set; }
        public string OilTypeCode { get; set; }
        public string OilClass { get; set; }
        public string OilCategory { get; set; }
        public Nullable<System.Guid> OilTypeID { get; set; }
        public string OilTypeDesc { get; set; }
        public Nullable<System.Guid> UOMID { get; set; }
        public string UOMCode { get; set; }
        public string UOMDesc { get; set; }
        public Nullable<double> EstOilMT { get; set; }
        public Nullable<System.Guid> CurrentFlowActionStatusID { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public string DraftBy { get; set; }
        public Nullable<System.DateTime> DraftDate { get; set; }
        public Nullable<bool> IsSubmit { get; set; }
        public string SubmitBy { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelBy { get; set; }
        public string CancelRemark { get; set; }
        public string RejectBy { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public string RejectRemark { get; set; }
        public Nullable<bool> IsAppCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<bool> IsPayment { get; set; }
        public Nullable<System.DateTime> PaymentTime { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentRefID { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string PermitQRCode { get; set; }
        public string PermitDocLink { get; set; }
        public string NPDocLink { get; set; }
        public string NPQRCode { get; set; }
        public string Lampiran1DocLink { get; set; }
        public string Lampiran1QRCode { get; set; }
        public string PermitIssuerUserID { get; set; }
        public Nullable<bool> IsSubmitBL { get; set; }
        public Nullable<System.DateTime> SubmitBLDate { get; set; }
        public string BLNo { get; set; }
        public Nullable<bool> IsAcknowledge { get; set; }
        public Nullable<bool> IsIntegrity { get; set; }
        public string IntegrityClauseEN { get; set; }
        public string IntegrityClauseMY { get; set; }
        public Nullable<bool> IsAcknowledgeBL { get; set; }
        public Nullable<bool> IsIntegrityBL { get; set; }
        public string IntegrityClauseENBL { get; set; }
        public string IntegrityClauseMYBL { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ActionStatus { get; set; }
        public string LabelColor { get; set; }
        public Nullable<System.Guid> FlowActionStatusID { get; set; }
        public Nullable<int> ActionStatusSeq { get; set; }
        public string BLAttachLink { get; set; }
        public Nullable<bool> IsSubmitCM { get; set; }
        public Nullable<System.DateTime> SubmitCMDate { get; set; }
        public string CMNo { get; set; }
        public string CMAttachLink { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<double> ActOilMT { get; set; }
        public Nullable<System.DateTime> ActOperationDateTime { get; set; }
        public Nullable<System.DateTime> ActOperationTime { get; set; }
        public Nullable<System.DateTime> ValidPermit { get; set; }
        public string VSSupritendentName { get; set; }
        public string VSSupritendentTelNo { get; set; }
        public string VRSupritendentName { get; set; }
        public string VRSupritendentTelNo { get; set; }
        public Nullable<bool> IsAmend { get; set; }
        public Nullable<bool> IsAmendApprove { get; set; }
        public Nullable<bool> IsCompleteDeclare { get; set; }
    }
}
