//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_opGroupEmail
    {
        public Nullable<System.Guid> FlowActionStatusID { get; set; }
        public string ActionStatus { get; set; }
        public string TempSubject { get; set; }
        public string TempBody { get; set; }
        public string ReceiptAG1 { get; set; }
        public Nullable<int> PortLoc { get; set; }
        public Nullable<System.Guid> PermitIssuerID { get; set; }
        public string PermitIssuer { get; set; }
        public System.Guid FlowActionEmailID { get; set; }
        public Nullable<System.Guid> EmailTempID { get; set; }
        public Nullable<System.Guid> ReceiptAGID { get; set; }
        public Nullable<bool> IsApplicant { get; set; }
        public Nullable<System.Guid> SupplyMethodID { get; set; }
        public Nullable<bool> IsOperator { get; set; }
        public Nullable<bool> IsEmailGroup { get; set; }
        public string EmailGroup { get; set; }
    }
}
