//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTSEmailServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Permit
    {
        public System.Guid OperationAppID { get; set; }
        public string CaseNum { get; set; }
        public string CompID { get; set; }
        public string CompanyName { get; set; }
        public string SOCompID { get; set; }
        public string SOCompanyName { get; set; }
        public string UserName { get; set; }
        public string ICNo { get; set; }
        public string Designation { get; set; }
        public string UsrTelNo { get; set; }
        public string usrFaxNo { get; set; }
        public string UsrEmailAdd { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string DeliveryLocation { get; set; }
        public string PermitIssuer { get; set; }
        public string VSName { get; set; }
        public string VSIMONo { get; set; }
        public string VSFlagName { get; set; }
        public string VSPortReg { get; set; }
        public Nullable<double> VSLOA { get; set; }
        public Nullable<double> VSGRT { get; set; }
        public Nullable<double> VSNRT { get; set; }
        public string VSMMSINo { get; set; }
        public string VSLastPortName { get; set; }
        public string VSNextPortName { get; set; }
        public string VRName { get; set; }
        public string VRIMONo { get; set; }
        public string VRFlagName { get; set; }
        public string VRPortReg { get; set; }
        public Nullable<double> VRLOA { get; set; }
        public Nullable<double> VRGRT { get; set; }
        public Nullable<double> VRNRT { get; set; }
        public string VRMMSINo { get; set; }
        public string VRLastPortName { get; set; }
        public string VRNextPortName { get; set; }
        public Nullable<System.DateTime> EstOperationDateTime { get; set; }
        public Nullable<System.DateTime> EstOperationTime { get; set; }
        public string OilTypeCode { get; set; }
        public string OilTypeDesc { get; set; }
        public string OilClass { get; set; }
        public string OilCategory { get; set; }
        public string UOMCode { get; set; }
        public Nullable<double> EstOilMT { get; set; }
        public string PortName { get; set; }
        public Nullable<bool> IsPayment { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ReceiptNo { get; set; }
        public string PaymentRefID { get; set; }
        public Nullable<System.DateTime> PaymentTime { get; set; }
        public string JLMName { get; set; }
        public string JLMUser { get; set; }
        public string JLMEmail { get; set; }
        public string JLMAdd1 { get; set; }
        public string JLMAdd2 { get; set; }
        public string JLMAdd3 { get; set; }
        public string JLMTelNo { get; set; }
        public string JLMFaxNo { get; set; }
        public string PermitQRCode { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string STSOperator { get; set; }
        public Nullable<int> VSLatDegree { get; set; }
        public Nullable<decimal> VSLatMin { get; set; }
        public Nullable<int> VRLatDegree { get; set; }
        public Nullable<decimal> VRLatMin { get; set; }
        public string MethodCode { get; set; }
        public Nullable<int> VSLongDegree { get; set; }
        public Nullable<decimal> VSLongMin { get; set; }
        public Nullable<int> VRLongDegree { get; set; }
        public Nullable<decimal> VRLongMin { get; set; }
        public string VSCallSign { get; set; }
        public string VRCallSign { get; set; }
    }
}
