//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessGroup
    {
        public System.Guid AccessGroupID { get; set; }
        public string AccessGroupName { get; set; }
        public string AccessGroupDesc { get; set; }
        public Nullable<System.Guid> MainPageId { get; set; }
        public Nullable<int> PortLoc { get; set; }
        public Nullable<System.Guid> PermitIssuerID { get; set; }
        public string UserManual { get; set; }
        public string Menu { get; set; }
        public Nullable<bool> IsEmailGroup { get; set; }
        public string EmailGroup { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
