//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBunkering.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public System.Guid EmailLogID { get; set; }
        public Nullable<System.Guid> ReferenceID { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<bool> IsSend { get; set; }
    }
}
