//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowActionEmail
    {
        public System.Guid FlowActionEmailID { get; set; }
        public Nullable<System.Guid> SupplyMethodID { get; set; }
        public Nullable<System.Guid> FlowActionStatusID { get; set; }
        public Nullable<System.Guid> EmailTempID { get; set; }
        public Nullable<System.Guid> ReceiptAGID { get; set; }
        public Nullable<bool> IsApplicant { get; set; }
        public Nullable<bool> IsOperator { get; set; }
    }
}
