//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicCompanyVessel
    {
        public System.Guid LicCompanyVesselID { get; set; }
        public Nullable<System.Guid> LicCompanyID { get; set; }
        public string ShipLicenseNo { get; set; }
        public Nullable<System.Guid> ShipID { get; set; }
        public string CompID { get; set; }
        public string OffNo { get; set; }
        public string ShipName { get; set; }
        public string PortReg { get; set; }
        public string CallSign { get; set; }
        public string IMONo { get; set; }
        public Nullable<int> YearReg { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<decimal> GRT { get; set; }
        public Nullable<decimal> NRT { get; set; }
        public Nullable<decimal> DWT { get; set; }
        public string ShipType { get; set; }
        public string VoyageType { get; set; }
        public Nullable<decimal> LOA { get; set; }
        public string Status { get; set; }
        public string OwnerName { get; set; }
        public string Owner { get; set; }
        public string ShipFlag { get; set; }
        public Nullable<decimal> Breadth { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> STDDraft { get; set; }
        public Nullable<decimal> ShipCapacity { get; set; }
        public Nullable<decimal> ShipBeam { get; set; }
        public Nullable<decimal> DispmtWeight { get; set; }
        public Nullable<System.DateTime> DSLValidFrom { get; set; }
        public Nullable<System.DateTime> DSLValidTo { get; set; }
        public Nullable<System.DateTime> STSPermitValidFrom { get; set; }
        public Nullable<System.DateTime> STSPermitValidTo { get; set; }
        public string MMSINo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> LatDegree { get; set; }
        public Nullable<decimal> LatMin { get; set; }
        public Nullable<decimal> LatSec { get; set; }
        public Nullable<int> LongDegree { get; set; }
        public Nullable<decimal> LongMin { get; set; }
        public Nullable<decimal> LongSec { get; set; }
        public string SupritendentName { get; set; }
        public string SupritendentTelNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
