//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MMSSyncEntities : DbContext
    {
        public MMSSyncEntities()
            : base("name=MMSSyncEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LicCompany> LicCompanies { get; set; }
        public DbSet<ShipFlag> ShipFlags { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Port> Ports { get; set; }
        public DbSet<ShipMaster> ShipMasters { get; set; }
        public DbSet<ShipType> ShipTypes { get; set; }
        public DbSet<v_ShipMaster> v_ShipMaster { get; set; }
        public DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public DbSet<ShipMaster3> ShipMaster3 { get; set; }
    }
}
