//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationAppAttach
    {
        public System.Guid AttachID { get; set; }
        public Nullable<System.Guid> OperationAppID { get; set; }
        public Nullable<System.Guid> AttchTypeID { get; set; }
        public string DocTitle { get; set; }
        public string Path { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
