//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingEmail
    {
        public System.Guid PendingMailID { get; set; }
        public Nullable<System.Guid> RefID { get; set; }
        public Nullable<System.Guid> RefFlowID { get; set; }
        public Nullable<bool> IsReject { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
    }
}
