//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Port
    {
        public string locode { get; set; }
        public string country_code { get; set; }
        public string country_name { get; set; }
        public string port_code { get; set; }
        public string port_name { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string update_user { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
