//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class eSTS_StagEntities : DbContext
    {
        public eSTS_StagEntities()
            : base("name=eSTS_StagEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public int SaveChanges(string userId, string keyName, Guid transID)
        {
            // Get all Added/Deleted/Modified entities (not Unmodified or Detached)
            foreach (var ent in this.ChangeTracker.Entries().Where(p => p.State == System.Data.EntityState.Added || p.State == System.Data.EntityState.Deleted || p.State == System.Data.EntityState.Modified))
            {
                // For each changed record, get the audit record entries and add them
                foreach (AuditLog x in GetAuditRecordsForChange(ent, userId, keyName, transID))
                {
                    this.AuditLogs.Add(x);
                }
            }

            // Call the original SaveChanges(), which will save both the changes made and the audit records
            return base.SaveChanges();
        }
        private List<AuditLog> GetAuditRecordsForChange(DbEntityEntry dbEntry, string userId, string keyName, Guid transID)
        {
            List<AuditLog> result = new List<AuditLog>();

            DateTime changeTime = DateTime.UtcNow;

            // Get the Table() attribute, if one exists
            //TableAttribute tableAttr = dbEntry.Entity.GetType().GetCustomAttributes(typeof(TableAttribute), false).SingleOrDefault() as TableAttribute;

            TableAttribute tableAttr = dbEntry.Entity.GetType().GetCustomAttributes(typeof(TableAttribute), true).SingleOrDefault() as TableAttribute;

            // Get table name (if it has a Table attribute, use that, otherwise get the pluralized name)
            string tableName = dbEntry.Entity.GetType().Name;//tableAttr != null ? tableAttr.Name : dbEntry.Entity.GetType().Name;

            // Get primary key value (If you have more than one key column, this will need to be adjusted)
            //var keyNames = dbEntry.Entity.GetType().GetProperties().Where(p => p.GetCustomAttributes(typeof(KeyAttribute), false).Count() > 0).ToList();

            // string keyName = "PIID";//keyNames[0].Name; //dbEntry.Entity.GetType().GetProperties().Single(p => p.GetCustomAttributes(typeof(KeyAttribute), false).Count() > 0).Name;

            if (dbEntry.State == System.Data.EntityState.Added)
            {
                // For Inserts, just add the whole record
                // If the entity implements IDescribableEntity, use the description from Describe(), otherwise use ToString()

                foreach (string propertyName in dbEntry.CurrentValues.PropertyNames)
                {
                    result.Add(new AuditLog()
                    {
                        Id = Guid.NewGuid(),
                        UserID = userId,
                        Date = changeTime,
                        AuditType = "A",    // Added
                        TableName = tableName,
                        PK = dbEntry.CurrentValues.GetValue<object>(keyName).ToString(),
                        ColumnName = propertyName,
                        TransID = transID,
                        NewValue = dbEntry.CurrentValues.GetValue<object>(propertyName) == null ? null : dbEntry.CurrentValues.GetValue<object>(propertyName).ToString()
                    }
                            );
                }
            }
            else if (dbEntry.State == System.Data.EntityState.Deleted)
            {
                // Same with deletes, do the whole record, and use either the description from Describe() or ToString()
                result.Add(new AuditLog()
                {
                    Id = Guid.NewGuid(),
                    UserID = userId,
                    Date = changeTime,
                    AuditType = "D", // Deleted
                    TableName = tableName,
                    PK = dbEntry.OriginalValues.GetValue<object>(keyName).ToString(),
                    ColumnName = "*ALL",
                    TransID = transID,
                    NewValue = dbEntry.OriginalValues.ToObject().ToString() //(dbEntry.OriginalValues.ToObject() is IDescribableEntity) ? (dbEntry.OriginalValues.ToObject() as IDescribableEntity).Describe() : dbEntry.OriginalValues.ToObject().ToString()
                }
                    );
            }
            else if (dbEntry.State == System.Data.EntityState.Modified)
            {
                foreach (string propertyName in dbEntry.OriginalValues.PropertyNames)
                {
                    // For updates, we only want to capture the columns that actually changed
                    if (!object.Equals(dbEntry.OriginalValues.GetValue<object>(propertyName), dbEntry.CurrentValues.GetValue<object>(propertyName)))
                    {
                        result.Add(new AuditLog()
                        {
                            Id = Guid.NewGuid(),
                            UserID = userId,
                            Date = changeTime,
                            AuditType = "M",    // Modified
                            TableName = tableName,
                            PK = dbEntry.OriginalValues.GetValue<object>(keyName).ToString(),
                            ColumnName = propertyName,
                            TransID = transID,
                            OldValue = dbEntry.OriginalValues.GetValue<object>(propertyName) == null ? null : dbEntry.OriginalValues.GetValue<object>(propertyName).ToString(),
                            NewValue = dbEntry.CurrentValues.GetValue<object>(propertyName) == null ? null : dbEntry.CurrentValues.GetValue<object>(propertyName).ToString()
                        }
                            );
                    }
                }
            }
            // Otherwise, don't do anything, we don't care about Unchanged or Detached entities

            return result;
        }


        public DbSet<AccessGroup> AccessGroups { get; set; }
        public DbSet<AccessGroupModule> AccessGroupModules { get; set; }
        public DbSet<AccessModule> AccessModules { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }
        public DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public DbSet<EmailModule> EmailModules { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<FlowActionEmail> FlowActionEmails { get; set; }
        public DbSet<FlowActionStatu> FlowActionStatus { get; set; }
        public DbSet<FlowModuleLayer> FlowModuleLayers { get; set; }
        public DbSet<LicCompany> LicCompanies { get; set; }
        public DbSet<LicCompanyAttach> LicCompanyAttaches { get; set; }
        public DbSet<LicCompanyVesselAttach> LicCompanyVesselAttaches { get; set; }
        public DbSet<log> logs { get; set; }
        public DbSet<ModuleAttachDoc> ModuleAttachDocs { get; set; }
        public DbSet<MSDeliveryLoc> MSDeliveryLocs { get; set; }
        public DbSet<MSDocType> MSDocTypes { get; set; }
        public DbSet<MSOilCategory> MSOilCategories { get; set; }
        public DbSet<MSOilClass> MSOilClasses { get; set; }
        public DbSet<MSOilType> MSOilTypes { get; set; }
        public DbSet<MSPermitIssuer> MSPermitIssuers { get; set; }
        public DbSet<MSPortLocation> MSPortLocations { get; set; }
        public DbSet<MSSupplyMethod> MSSupplyMethods { get; set; }
        public DbSet<MSUOM> MSUOMs { get; set; }
        public DbSet<OpAppointAgent> OpAppointAgents { get; set; }
        public DbSet<OpCaseNum> OpCaseNums { get; set; }
        public DbSet<OperationAppAttach> OperationAppAttaches { get; set; }
        public DbSet<OperationAppFlow> OperationAppFlows { get; set; }
        public DbSet<OwnerInfo> OwnerInfoes { get; set; }
        public DbSet<PendingEmail> PendingEmails { get; set; }
        public DbSet<TblMailServer> TblMailServers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<v_AccessGroupModule> v_AccessGroupModule { get; set; }
        public DbSet<v_AccessModule> v_AccessModule { get; set; }
        public DbSet<v_AdminUsers> v_AdminUsers { get; set; }
        public DbSet<v_AppointAgent> v_AppointAgent { get; set; }
        public DbSet<v_AppointAgentNew> v_AppointAgentNew { get; set; }
        public DbSet<v_FlowActionStatus> v_FlowActionStatus { get; set; }
        public DbSet<v_IntegrationFlow> v_IntegrationFlow { get; set; }
        public DbSet<v_LicCompany> v_LicCompany { get; set; }
        public DbSet<v_LicCompanyActive> v_LicCompanyActive { get; set; }
        public DbSet<v_LicCompanyAttach> v_LicCompanyAttach { get; set; }
        public DbSet<v_LicCompanyVesselAttach> v_LicCompanyVesselAttach { get; set; }
        public DbSet<v_OperationAppAttach> v_OperationAppAttach { get; set; }
        public DbSet<v_OperationAppFlow> v_OperationAppFlow { get; set; }
        public DbSet<v_opGroupEmail> v_opGroupEmail { get; set; }
        public DbSet<v_STSOperator> v_STSOperator { get; set; }
        public DbSet<v_SuppDoc> v_SuppDoc { get; set; }
        public DbSet<v_UsersSASO> v_UsersSASO { get; set; }
        public DbSet<EmailSendLog> EmailSendLogs { get; set; }
        public DbSet<LicCompanyVessel> LicCompanyVessels { get; set; }
        public DbSet<v_OpLicCompanyVessel> v_OpLicCompanyVessel { get; set; }
        public DbSet<v_Permit> v_Permit { get; set; }
        public DbSet<OperationApp> OperationApps { get; set; }
        public DbSet<SystemParam> SystemParams { get; set; }
        public DbSet<v_OperationApp> v_OperationApp { get; set; }
        public DbSet<v_users> v_users { get; set; }
        public DbSet<v_Integration> v_Integration { get; set; }
        public DbSet<v_ReportQlik> v_ReportQlik { get; set; }
    }
}
