//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParam
    {
        public System.Guid SystemParamID { get; set; }
        public string OperationPGCaseNum { get; set; }
        public string OperationTPCaseNum { get; set; }
        public Nullable<System.Guid> SupplyMethodA { get; set; }
        public Nullable<System.Guid> SupplyMethodB { get; set; }
        public Nullable<System.Guid> FlowDraft { get; set; }
        public Nullable<System.Guid> FlowSubmit { get; set; }
        public Nullable<System.Guid> FlowPendingApproval { get; set; }
        public Nullable<System.Guid> FlowApproved { get; set; }
        public Nullable<System.Guid> FlowPendingPayment { get; set; }
        public Nullable<System.Guid> FlowPermitIssued { get; set; }
        public Nullable<System.Guid> FlowPendingCM { get; set; }
        public Nullable<System.Guid> FlowPendingBL { get; set; }
        public Nullable<System.Guid> FlowCancel { get; set; }
        public Nullable<System.Guid> FlowReject { get; set; }
        public Nullable<System.Guid> FlowSubmitDec { get; set; }
        public Nullable<System.Guid> FlowPendingVerifyDec { get; set; }
        public Nullable<System.Guid> FlowVerifiedDec { get; set; }
        public Nullable<System.Guid> FlowPendingApproveDec { get; set; }
        public Nullable<System.Guid> FlowApprovedDec { get; set; }
        public Nullable<System.Guid> FlowRejectDec { get; set; }
        public Nullable<System.Guid> FlowProcessInvoice { get; set; }
        public Nullable<System.Guid> FlowInvoicePrepared { get; set; }
        public Nullable<System.Guid> FlowComplete { get; set; }
        public Nullable<System.Guid> FlowAmendSubmit { get; set; }
        public Nullable<System.Guid> FlowAmendPending { get; set; }
        public Nullable<System.Guid> FlowAmendApproved { get; set; }
        public Nullable<System.Guid> FlowAmendRejected { get; set; }
        public string SysURL { get; set; }
    }
}
