//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMailServer
    {
        public int MailServerID { get; set; }
        public Nullable<int> DBNo { get; set; }
        public string SMTPAddress { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public string SMTPUsername { get; set; }
        public string SMTPPassword { get; set; }
        public Nullable<int> SMTPRequiredAuth { get; set; }
        public Nullable<int> SMTPRequiredSSL { get; set; }
        public string SMTPAddressIncoming { get; set; }
        public Nullable<int> SMTPPortIncoming { get; set; }
    }
}
