//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid id { get; set; }
        public string OrgzID { get; set; }
        public string UserID { get; set; }
        public string UserPass { get; set; }
        public string UserPass2 { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string TelNo { get; set; }
        public string ICNo { get; set; }
        public string Designation { get; set; }
        public Nullable<System.Guid> AccessGroupID { get; set; }
        public Nullable<System.Guid> STSAccessGroupID { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
