//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AccessModule
    {
        public Nullable<long> UniqueId { get; set; }
        public System.Guid lvl0ID { get; set; }
        public string lvl0Desc { get; set; }
        public Nullable<int> lvl0Seq { get; set; }
        public Nullable<System.Guid> lvl1ID { get; set; }
        public string lvl1Desc { get; set; }
        public Nullable<int> lvl1Seq { get; set; }
        public Nullable<System.Guid> lvl2ID { get; set; }
        public string lvl2Desc { get; set; }
        public Nullable<int> lvl2Seq { get; set; }
    }
}
