//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AppointAgent
    {
        public System.Guid OpAppointAgentID { get; set; }
        public System.Guid LicCompanyID { get; set; }
        public string SACompID { get; set; }
        public string SACompName { get; set; }
        public string SOCompID { get; set; }
        public string SOCompName { get; set; }
        public Nullable<System.DateTime> AppointStartDate { get; set; }
        public Nullable<System.DateTime> AppointEndDate { get; set; }
        public string PortName { get; set; }
        public Nullable<int> Location { get; set; }
        public string ServiceCode { get; set; }
        public string AppointAttachLink { get; set; }
        public Nullable<System.Guid> SOLicenseID { get; set; }
        public Nullable<System.Guid> LicenseID { get; set; }
        public string VesselName { get; set; }
        public string VesselIMO { get; set; }
        public Nullable<System.DateTime> DtLicExp { get; set; }
    }
}
