//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_IntegrationFlow
    {
        public string ID_status { get; set; }
        public System.Guid OperationAppID { get; set; }
        public string status { get; set; }
        public Nullable<int> sequence { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isSync { get; set; }
        public string jbar_batchid { get; set; }
        public string jbar_custid { get; set; }
        public Nullable<System.DateTime> jbar_invdate { get; set; }
        public Nullable<System.DateTime> jbar_posteddate { get; set; }
        public string jbar_invoiceno { get; set; }
        public string AmendRemarks { get; set; }
    }
}
