//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Integration
    {
        public string CaseNum { get; set; }
        public string AgentID { get; set; }
        public string AgentName { get; set; }
        public string CompID { get; set; }
        public string CompanyName { get; set; }
        public System.Guid OperationAppID { get; set; }
        public string FSU { get; set; }
        public string FSUIMONo { get; set; }
        public string FSULastPort { get; set; }
        public string FSUNextPort { get; set; }
        public string VesselName { get; set; }
        public string VesselIMONo { get; set; }
        public string VesselLastPort { get; set; }
        public string VesselNextPort { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string OilTypeDesc { get; set; }
        public Nullable<double> ActOilMT { get; set; }
        public string UOMCode { get; set; }
        public string UOMDesc { get; set; }
        public string CMAttachLink { get; set; }
        public string BLAttachLink { get; set; }
    }
}
