//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ReportQlik
    {
        public string MethodCode { get; set; }
        public Nullable<System.Guid> OperationAppID { get; set; }
        public string AgentID { get; set; }
        public string AgentName { get; set; }
        public string OperatorID { get; set; }
        public string OperatorName { get; set; }
        public string DeliveryLocation { get; set; }
        public string FSUIMONo { get; set; }
        public string FSUName { get; set; }
        public Nullable<int> Yr { get; set; }
        public Nullable<int> Mth { get; set; }
        public string MonthDesc { get; set; }
        public Nullable<System.DateTime> ActOperationTime { get; set; }
        public Nullable<double> ActOilMT { get; set; }
        public string OilTypeCode { get; set; }
        public string OilTypeDesc { get; set; }
        public string ActionStatus { get; set; }
    }
}
