//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ShipMaster
    {
        public System.Guid ShipID { get; set; }
        public string ShipCategory { get; set; }
        public string OffNo { get; set; }
        public string ShipName { get; set; }
        public string PortReg { get; set; }
        public string CallSign { get; set; }
        public string IMONo { get; set; }
        public string RegNo { get; set; }
        public Nullable<int> YearReg { get; set; }
        public string ShipType { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<decimal> LOA { get; set; }
        public Nullable<decimal> Breadth { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> GRT { get; set; }
        public Nullable<decimal> NRT { get; set; }
        public Nullable<decimal> DWT { get; set; }
        public string IMOCode { get; set; }
        public string OwnerName { get; set; }
        public string ShipFlag { get; set; }
        public string BoatLicense { get; set; }
        public string Status { get; set; }
        public string VoyageType { get; set; }
        public Nullable<decimal> STDDraft { get; set; }
        public Nullable<decimal> ShipCapacity { get; set; }
        public Nullable<decimal> ShipBeam { get; set; }
        public Nullable<decimal> DispmtWeight { get; set; }
        public string ShipTypeID { get; set; }
    }
}
