//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SuppDoc
    {
        public string DocCode { get; set; }
        public string DocDesc { get; set; }
        public string ModuleID { get; set; }
        public string ModuleDesc { get; set; }
        public System.Guid MSDocTypeID { get; set; }
        public string DocType { get; set; }
        public Nullable<int> DocStatus { get; set; }
        public System.Guid ModuleAttachID { get; set; }
    }
}
