//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_UsersSASO
    {
        public System.Guid id { get; set; }
        public string ROCNO { get; set; }
        public string CompanyName { get; set; }
        public string UserID { get; set; }
        public string UserPass { get; set; }
        public string UserPass2 { get; set; }
        public string FullName { get; set; }
        public string EmailAdd { get; set; }
        public string MMSUserGroup { get; set; }
        public System.Guid AccessGroupID { get; set; }
        public string AccessGroupName { get; set; }
        public string AccessGroupDesc { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ModuleLink { get; set; }
        public int PortLoc { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string ContactPerson { get; set; }
        public string UserType { get; set; }
        public string AgentCode { get; set; }
        public string UsrTelNo { get; set; }
        public string ICNo { get; set; }
        public string Designation { get; set; }
    }
}
